# Generated by Django 6.0 on 2026-01-03 05:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DDSArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('income', 'Доход'), ('expense', 'Расход')], max_length=10)),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['kind', 'name'],
                'constraints': [models.UniqueConstraint(fields=('kind', 'name'), name='uniq_dds_article_kind_name')],
            },
        ),
        migrations.CreateModel(
            name='DDSOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('happened_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('method', models.CharField(choices=[('cash', 'Наличные'), ('card', 'Карта/терминал'), ('transfer', 'Перевод')], default='cash', max_length=12)),
                ('counterparty', models.CharField(blank=True, max_length=180)),
                ('comment', models.TextField(blank=True)),
                ('source', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_voided', models.BooleanField(default=False)),
                ('void_reason', models.CharField(blank=True, max_length=255)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ops', to='dds.ddsarticle')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dds_created', to=settings.AUTH_USER_MODEL)),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dds_voided', to=settings.AUTH_USER_MODEL)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dds_ops', to='dds.hotel')),
            ],
            options={
                'ordering': ['-happened_at', '-id'],
                'indexes': [models.Index(fields=['hotel', 'happened_at'], name='dds_ddsoper_hotel_i_6b72ae_idx'), models.Index(fields=['article', 'happened_at'], name='dds_ddsoper_article_1d5d95_idx')],
            },
        ),
    ]
