# Generated by Django 6.0 on 2026-01-04 13:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dds', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ddsarticle',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='активно?'),
        ),
        migrations.AlterField(
            model_name='ddsarticle',
            name='kind',
            field=models.CharField(choices=[('income', 'Доход'), ('expense', 'Расход')], max_length=10, verbose_name='Вид'),
        ),
        migrations.AlterField(
            model_name='ddsarticle',
            name='name',
            field=models.CharField(max_length=120, verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='ddsoperation',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='сумма'),
        ),
        migrations.AlterField(
            model_name='ddsoperation',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ops', to='dds.ddsarticle', verbose_name='статья'),
        ),
        migrations.AlterField(
            model_name='ddsoperation',
            name='comment',
            field=models.TextField(blank=True, verbose_name='комментарии'),
        ),
        migrations.AlterField(
            model_name='ddsoperation',
            name='counterparty',
            field=models.CharField(blank=True, max_length=180, verbose_name='поставщик/гость/компания'),
        ),
        migrations.AlterField(
            model_name='ddsoperation',
            name='happened_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата'),
        ),
        migrations.AlterField(
            model_name='ddsoperation',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dds_ops', to='dds.hotel', verbose_name='отель'),
        ),
        migrations.AlterField(
            model_name='ddsoperation',
            name='method',
            field=models.CharField(choices=[('cash', 'Наличные'), ('mkassa', 'Mkassa'), ('zadatok', 'Задаток'), ('optima', 'Оптима')], default='cash', max_length=12, verbose_name='способ оплаты'),
        ),
        migrations.AlterField(
            model_name='ddsoperation',
            name='source',
            field=models.CharField(blank=True, max_length=120, verbose_name='источник'),
        ),
        migrations.CreateModel(
            name='CashIncasso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='сумма')),
                ('happened_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата')),
                ('method', models.CharField(choices=[('cash', 'Наличные'), ('mkassa', 'Mkassa'), ('zadatok', 'Задаток'), ('optima', 'Оптима')], default='cash', max_length=12, verbose_name='с какого счета')),
                ('comment', models.TextField(blank=True, verbose_name='комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incasso_created', to=settings.AUTH_USER_MODEL, verbose_name='создал')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incassos', to='dds.hotel', verbose_name='отель')),
            ],
            options={
                'ordering': ['-happened_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CashRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Наличные (касса)')),
                ('mkassa_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Mkassa')),
                ('zadatok_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Задаток')),
                ('optima_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Оптима')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cash_register', to='dds.hotel', verbose_name='отель')),
            ],
        ),
        migrations.CreateModel(
            name='CashMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('in', 'Приход'), ('out', 'Расход/Списание')], max_length=3)),
                ('account', models.CharField(choices=[('cash', 'Наличные'), ('mkassa', 'Mkassa'), ('zadatok', 'Задаток'), ('optima', 'Оптима')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('happened_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_moves_created', to=settings.AUTH_USER_MODEL)),
                ('dds_operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_moves', to='dds.ddsoperation')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_movements', to='dds.hotel')),
                ('incasso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_moves', to='dds.cashincasso')),
                ('register', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='dds.cashregister')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('dds_operation__isnull', False)), fields=('dds_operation', 'account', 'direction'), name='uniq_cashmove_dds_account_dir')],
            },
        ),
    ]
