# Generated by Django 6.0 on 2026-01-04 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dds', '0002_alter_ddsarticle_is_active_alter_ddsarticle_kind_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DDSCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('income', 'Доход'), ('expense', 'Расход')], max_length=10, verbose_name='Вид')),
                ('name', models.CharField(max_length=120, verbose_name='Категория')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['kind', 'parent_id', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='ddsarticle',
            options={'ordering': ['kind', 'category_id', 'name']},
        ),
        migrations.RemoveConstraint(
            model_name='ddsarticle',
            name='uniq_dds_article_kind_name',
        ),
        migrations.AddField(
            model_name='ddscategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='dds.ddscategory', verbose_name='Родительская категория'),
        ),
        migrations.AddField(
            model_name='ddsarticle',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='dds.ddscategory', verbose_name='Категория'),
        ),
        migrations.AddConstraint(
            model_name='ddsarticle',
            constraint=models.UniqueConstraint(fields=('kind', 'category', 'name'), name='uniq_dds_article_kind_cat_name'),
        ),
        migrations.AddConstraint(
            model_name='ddscategory',
            constraint=models.UniqueConstraint(fields=('kind', 'parent', 'name'), name='uniq_dds_category_kind_parent_name'),
        ),
    ]
