# Generated by Django 6.0 on 2026-01-07 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dds', '0003_ddscategory_alter_ddsarticle_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashincasso',
            options={'ordering': ['-happened_at', '-id'], 'verbose_name': 'Инкассация', 'verbose_name_plural': 'Инкассации'},
        ),
        migrations.AlterModelOptions(
            name='cashmovement',
            options={'ordering': ['-happened_at', '-id'], 'verbose_name': 'Движение денег', 'verbose_name_plural': 'Движения денег'},
        ),
        migrations.AlterModelOptions(
            name='cashregister',
            options={'ordering': ['hotel__name'], 'verbose_name': 'Касса', 'verbose_name_plural': 'Кассы'},
        ),
        migrations.AlterModelOptions(
            name='ddsarticle',
            options={'ordering': ['kind', 'category_id', 'name'], 'verbose_name': 'Статья ДДС', 'verbose_name_plural': 'Статьи ДДС'},
        ),
        migrations.AlterModelOptions(
            name='ddscategory',
            options={'ordering': ['kind', 'parent_id', 'name'], 'verbose_name': 'Категория ДДС', 'verbose_name_plural': 'Категории ДДС'},
        ),
        migrations.AlterModelOptions(
            name='ddsoperation',
            options={'ordering': ['-happened_at', '-id'], 'verbose_name': 'Операция ДДС', 'verbose_name_plural': 'Операции ДДС'},
        ),
        migrations.AlterModelOptions(
            name='hotel',
            options={'ordering': ['name'], 'verbose_name': 'Отель', 'verbose_name_plural': 'Отели'},
        ),
    ]
