# Generated by Django 6.0 on 2026-01-08 11:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dds', '0004_alter_cashincasso_options_alter_cashmovement_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_account', models.CharField(choices=[('cash', 'Наличные'), ('mkassa', 'Mkassa'), ('zadatok', 'Задаток'), ('optima', 'Оптима')], max_length=10, verbose_name='Со счета')),
                ('to_account', models.CharField(choices=[('cash', 'Наличные'), ('mkassa', 'Mkassa'), ('zadatok', 'Задаток'), ('optima', 'Оптима')], max_length=10, verbose_name='На счет')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма')),
                ('happened_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_voided', models.BooleanField(default=False)),
                ('void_reason', models.CharField(blank=True, max_length=255)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_transfers_created', to=settings.AUTH_USER_MODEL)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_transfers', to='dds.hotel', verbose_name='Отель')),
                ('register', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers', to='dds.cashregister', verbose_name='Касса')),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cash_transfers_voided', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Перевод между счетами',
                'verbose_name_plural': 'Переводы между счетами',
                'ordering': ['-happened_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='cashmovement',
            name='transfer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='dds.cashtransfer', verbose_name='Перевод'),
        ),
        migrations.AddIndex(
            model_name='cashtransfer',
            index=models.Index(fields=['hotel', 'happened_at'], name='dds_cashtra_hotel_i_f361ea_idx'),
        ),
    ]
