# Generated by Django 6.0 on 2026-01-12 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dds', '0005_cashtransfer_cashmovement_transfer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ddsarticle',
            name='hotels',
            field=models.ManyToManyField(blank=True, help_text='Если не выбрать ничего — статья будет доступна во всех отелях.', related_name='dds_articles', to='dds.hotel', verbose_name='Отели (где доступна статья)'),
        ),
    ]
