# Generated by Django 6.0.3 on 2026-03-17 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dds', '0006_ddsarticle_hotels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashincasso',
            name='method',
            field=models.CharField(choices=[('cash', 'Наличные'), ('mkassa', 'Банк1'), ('zadatok', 'Задаток'), ('optima', 'Банк2')], default='cash', max_length=12, verbose_name='с какого счета'),
        ),
        migrations.AlterField(
            model_name='cashmovement',
            name='account',
            field=models.CharField(choices=[('cash', 'Наличные'), ('mkassa', 'Банк1'), ('zadatok', 'Задаток'), ('optima', 'Банк2')], max_length=10),
        ),
        migrations.AlterField(
            model_name='cashtransfer',
            name='from_account',
            field=models.CharField(choices=[('cash', 'Наличные'), ('mkassa', 'Банк1'), ('zadatok', 'Задаток'), ('optima', 'Банк2')], max_length=10, verbose_name='Со счета'),
        ),
        migrations.AlterField(
            model_name='cashtransfer',
            name='to_account',
            field=models.CharField(choices=[('cash', 'Наличные'), ('mkassa', 'Банк1'), ('zadatok', 'Задаток'), ('optima', 'Банк2')], max_length=10, verbose_name='На счет'),
        ),
        migrations.AlterField(
            model_name='ddsoperation',
            name='method',
            field=models.CharField(choices=[('cash', 'Наличные'), ('mkassa', 'Банк1'), ('zadatok', 'Задаток'), ('optima', 'Банк2')], default='cash', max_length=12, verbose_name='способ оплаты'),
        ),
    ]
