# Generated by Django 6.0 on 2026-01-07 08:48

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dds', '0004_alter_cashincasso_options_alter_cashmovement_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Компания')),
                ('inn', models.CharField(blank=True, max_length=14, verbose_name='ИНН (опционально)')),
                ('contact_name', models.CharField(blank=True, max_length=200, verbose_name='Контактное лицо')),
                ('contact_phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('pay_terms', models.CharField(choices=[('now', 'Оплата сразу'), ('weekly', 'Раз в неделю'), ('invoice', 'По счету')], default='now', max_length=10, verbose_name='Условия оплаты')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CompanyFolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Кредитный лимит')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='folios', to='pms.company', verbose_name='Компания')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='company_folios', to='dds.hotel', verbose_name='Отель')),
            ],
            options={
                'verbose_name': 'Фолио компании',
                'verbose_name_plural': 'Фолио компаний',
                'ordering': ['hotel_id', 'company__name'],
            },
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=180, verbose_name='ФИО')),
                ('inn', models.CharField(blank=True, max_length=14, verbose_name='ИНН (если есть)')),
                ('nationality', models.CharField(blank=True, max_length=80, verbose_name='Национальность')),
                ('is_foreigner', models.BooleanField(default=False, verbose_name='Иностранец')),
                ('doc_number', models.CharField(blank=True, max_length=80, verbose_name='Документ (паспорт/ID)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='guests', to='dds.hotel', verbose_name='Отель')),
            ],
            options={
                'verbose_name': 'Гость',
                'verbose_name_plural': 'Гости',
                'ordering': ['hotel_id', 'full_name'],
            },
        ),
        migrations.CreateModel(
            name='HotelPMSSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False, verbose_name='Шахматка включена')),
                ('check_in_time', models.TimeField(default=datetime.time(14, 0), verbose_name='Время заезда')),
                ('check_out_time', models.TimeField(default=datetime.time(12, 0), verbose_name='Время выезда')),
                ('mode', models.CharField(choices=[('daily', 'Посуточно'), ('hourly', 'Почасово')], default='daily', max_length=10, verbose_name='Режим')),
                ('hotel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pms_settings', to='dds.hotel')),
            ],
            options={
                'verbose_name': 'Настройки PMS',
                'verbose_name_plural': 'Настройки PMS',
            },
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Тип номера')),
                ('default_capacity', models.PositiveSmallIntegerField(default=2, verbose_name='Вместимость по умолчанию')),
                ('default_day_rate', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Тариф/сутки по умолчанию')),
                ('default_hour_rate', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Тариф/час по умолчанию')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='room_types', to='dds.hotel', verbose_name='Отель')),
            ],
            options={
                'verbose_name': 'Тип номера',
                'verbose_name_plural': 'Типы номеров',
                'ordering': ['hotel_id', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, verbose_name='Номер/название')),
                ('floor', models.IntegerField(default=1, verbose_name='Этаж')),
                ('capacity', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Вместимость (если отличается)')),
                ('day_rate', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Тариф/сутки')),
                ('hour_rate', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Тариф/час')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_out_of_service', models.BooleanField(default=False, verbose_name='На ремонте')),
                ('clean_status', models.CharField(choices=[('clean', 'Убран'), ('dirty', 'Не убран'), ('progress', 'Уборка')], default='clean', max_length=10, verbose_name='Уборка')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='dds.hotel', verbose_name='Отель')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='pms.roomtype', verbose_name='Тип номера')),
            ],
            options={
                'verbose_name': 'Номер',
                'verbose_name_plural': 'Номера',
                'ordering': ['hotel_id', 'floor', 'number'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_no', models.CharField(blank=True, max_length=32, verbose_name='№ смены')),
                ('booked_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата брони')),
                ('booking_number', models.CharField(max_length=64, verbose_name='Номер брони')),
                ('stay_type', models.CharField(choices=[('private', 'Частный'), ('corporate', 'Корпоративный')], default='private', max_length=10, verbose_name='Тип')),
                ('guest_name', models.CharField(max_length=180, verbose_name='Гость (имя)')),
                ('guest_phone', models.CharField(blank=True, max_length=60, verbose_name='Телефон')),
                ('operation_type', models.CharField(choices=[('book', 'Бронь'), ('cancel', 'Отмена'), ('edit', 'Изменение')], default='book', max_length=10, verbose_name='Тип операции')),
                ('guests_count', models.PositiveSmallIntegerField(default=1, verbose_name='Количество гостей')),
                ('check_in', models.DateField(verbose_name='Дата заезда')),
                ('check_out', models.DateField(verbose_name='Дата выезда')),
                ('price_per_night', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Сумма за ночь')),
                ('commission_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Комиссия за бронь')),
                ('gross_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Общая сумма (до комиссии)')),
                ('payment_status', models.CharField(choices=[('unpaid', 'Не оплачено'), ('partial', 'Частично'), ('paid', 'Оплачено')], default='unpaid', max_length=10, verbose_name='Статус оплаты')),
                ('channel', models.CharField(blank=True, max_length=80, verbose_name='Канал брони')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('confirmed', 'Подтверждена'), ('no_show', 'Не заехал'), ('cancelled', 'Отменена')], default='new', max_length=12, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings_created', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='dds.hotel', verbose_name='Отель')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='pms.company', verbose_name='Компания')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pms.room', verbose_name='Номер')),
                ('room_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pms.roomtype', verbose_name='Тип номера')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
                'ordering': ['-booked_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Stay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stay_type', models.CharField(choices=[('private', 'Частный'), ('corporate', 'Корпоративный')], default='private', max_length=10, verbose_name='Тип')),
                ('guest_name', models.CharField(blank=True, max_length=200, verbose_name='Гость (ФИО)')),
                ('guest_phone', models.CharField(blank=True, max_length=60, verbose_name='Телефон')),
                ('check_in', models.DateTimeField(verbose_name='Заезд')),
                ('check_out', models.DateTimeField(verbose_name='Выезд')),
                ('guests_count', models.PositiveSmallIntegerField(default=1, verbose_name='Кол-во гостей')),
                ('channel', models.CharField(blank=True, max_length=80, verbose_name='Канал (для УНО)')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Сумма')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Скидка')),
                ('tourist_tax_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Тур. сбор (итого)')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('status', models.CharField(choices=[('booked', 'Бронь'), ('in', 'Проживает'), ('out', 'Выехал'), ('canceled', 'Отменено'), ('no_show', 'Не заехал')], default='booked', max_length=12, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stays', to='pms.booking', verbose_name='Бронь (источник)')),
                ('cash_movement', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dds.cashmovement', verbose_name='Кассовое движение')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stays', to='pms.company', verbose_name='Компания')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stays_created', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('dds_operation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dds.ddsoperation', verbose_name='Запись ДДС')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stays', to='dds.hotel', verbose_name='Отель')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stays', to='pms.room', verbose_name='Номер')),
            ],
            options={
                'verbose_name': 'Проживание (шахматка)',
                'verbose_name_plural': 'Проживания (шахматка)',
                'ordering': ['-check_in', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CompanyFolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('charge', 'Начисление'), ('payment', 'Оплата'), ('adjust', 'Корректировка')], max_length=10, verbose_name='Тип')),
                ('happened_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата/время')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Описание')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='folio_items', to='pms.booking', verbose_name='Бронь')),
                ('cash_movement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='folio_items', to='dds.cashmovement')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='folio_items_created', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('dds_operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='folio_items', to='dds.ddsoperation')),
                ('folio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pms.companyfolio', verbose_name='Фолио')),
                ('stay', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='folio_items', to='pms.stay', verbose_name='Проживание')),
            ],
            options={
                'verbose_name': 'Строка фолио',
                'verbose_name_plural': 'Строки фолио',
                'ordering': ['-happened_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='StayGuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tourist_tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Тур. налог (по гостю)')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='guest_stays', to='pms.guest', verbose_name='Гость')),
                ('stay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stay_guests', to='pms.stay', verbose_name='Проживание')),
            ],
            options={
                'verbose_name': 'Гость в проживании',
                'verbose_name_plural': 'Гости в проживании',
            },
        ),
        migrations.AddConstraint(
            model_name='companyfolio',
            constraint=models.UniqueConstraint(fields=('hotel', 'company'), name='uniq_folio_hotel_company'),
        ),
        migrations.AddIndex(
            model_name='guest',
            index=models.Index(fields=['hotel', 'is_foreigner'], name='pms_guest_hotel_i_3ad11d_idx'),
        ),
        migrations.AddConstraint(
            model_name='roomtype',
            constraint=models.UniqueConstraint(fields=('hotel', 'name'), name='uniq_roomtype_hotel_name'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['hotel', 'is_active', 'is_out_of_service'], name='pms_room_hotel_i_65dd01_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['hotel', 'floor'], name='pms_room_hotel_i_9c0b5e_idx'),
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.UniqueConstraint(fields=('hotel', 'number'), name='uniq_room_hotel_number'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['hotel', 'check_in', 'check_out'], name='pms_booking_hotel_i_2c4251_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['hotel', 'booked_at'], name='pms_booking_hotel_i_038918_idx'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(fields=('hotel', 'booking_number'), name='uniq_booking_hotel_number'),
        ),
        migrations.AddIndex(
            model_name='stay',
            index=models.Index(fields=['hotel', 'status'], name='pms_stay_hotel_i_703d84_idx'),
        ),
        migrations.AddIndex(
            model_name='stay',
            index=models.Index(fields=['hotel', 'room', 'check_in', 'check_out'], name='pms_stay_hotel_i_e0c510_idx'),
        ),
        migrations.AddIndex(
            model_name='stay',
            index=models.Index(fields=['company', 'check_in'], name='pms_stay_company_e09277_idx'),
        ),
        migrations.AddIndex(
            model_name='companyfolioitem',
            index=models.Index(fields=['folio', 'happened_at'], name='pms_company_folio_i_cbec1a_idx'),
        ),
        migrations.AddConstraint(
            model_name='stayguest',
            constraint=models.UniqueConstraint(fields=('stay', 'guest'), name='uniq_stay_guest'),
        ),
    ]
