# Generated by Django 6.0 on 2026-01-07 09:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dds', '0004_alter_cashincasso_options_alter_cashmovement_options_and_more'),
        ('pms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyfolio',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': 'Фолио компании', 'verbose_name_plural': 'Фолио компаний'},
        ),
        migrations.RemoveField(
            model_name='companyfolio',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='companyfolio',
            name='credit_limit',
        ),
        migrations.RemoveField(
            model_name='companyfolioitem',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='companyfolioitem',
            name='kind',
        ),
        migrations.RemoveField(
            model_name='companyfolioitem',
            name='stay',
        ),
        migrations.AddField(
            model_name='companyfolio',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата закрытия'),
        ),
        migrations.AddField(
            model_name='companyfolio',
            name='is_closed',
            field=models.BooleanField(default=False, verbose_name='Закрыто'),
        ),
        migrations.AddField(
            model_name='companyfolioitem',
            name='item_type',
            field=models.CharField(blank=True, choices=[('charge', 'Начисление'), ('payment', 'Оплата'), ('adjust', 'Корректировка')], max_length=12, null=True, verbose_name='Тип'),
        ),
        migrations.AddField(
            model_name='companyfolioitem',
            name='signed_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Сумма (со знаком)'),
        ),
        migrations.AddField(
            model_name='companyfolioitem',
            name='stay_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID проживания (если нужно)'),
        ),
        migrations.AlterField(
            model_name='companyfolio',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='companyfolioitem',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='folio_items_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='companyfolioitem',
            name='happened_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата'),
        ),
        migrations.AddIndex(
            model_name='companyfolio',
            index=models.Index(fields=['hotel', 'is_closed'], name='pms_company_hotel_i_e6fe74_idx'),
        ),
        migrations.AddIndex(
            model_name='companyfolio',
            index=models.Index(fields=['company'], name='pms_company_company_e9cb58_idx'),
        ),
        migrations.AddIndex(
            model_name='companyfolioitem',
            index=models.Index(fields=['item_type'], name='pms_company_item_ty_dea985_idx'),
        ),
    ]
